### ISSUE TITLE
mypaint not finding json

### ISSUE THREAD

**Issue by quantizationbit** [igorek7/SlackBuilds#1]
I'm trying to build a dependency mypaint out of SBo and it is failing against json-c and it appears that the json lib has been renamed.  How are you working around this and making your SlackBuild work for you?

**Comment by igorek7** [comment]
Slackware-current (pre 14.2) includes now the json-c library, therefore you will not find it on the SBo current. I have not installed mypaint from the SBo, but if you are having troubles with the SBo scripts, I would suggest to ask [SlackBuilds.org Users List](https://www.mail-archive.com/slackbuilds-users@slackbuilds.org/info.html)
